server:
  port: 2222
spring:
  application:
    name: callHello
eureka:
  instance:
    # 心跳检测检测与续约时间,每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务,告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
sayHello: 
  ribbon: 
    NFLoadBalancerRuleClassName: com.controller.MyRule
    NFLoadBalancerPingClassName: com.controller.MyPing
    listOfServers: http://localhost:1111/,http://localhost:1112/,http://localhost:1113