server:
  port: 8889
spring: 
  application: 
    name: ekServer2
eureka: 
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
  instance: 
    hostname: ekServer2
  client:
    service-url:
      defaultZone: http://ekServer1:8888/eureka/