server:
  port: 8888
spring:
  application:
    name: ekServer1
eureka: 
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
  instance: 
    hostname: ekServer1
  client:
    service-url:
      defaultZone: http://ekServer2:8889/eureka/